name: 'Setup ts'
description: 'Setup node'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node_verion }}
    - uses: actions/cache@v2
      name: Cache node_modules
      id: cache-node-modules
      with:
        path: |
          ./node_modules/
        key: solana-${{ runner.os }}-v0000-${{ env.node_version }}-${{ hashFiles('./**/package-lock.json') }}
    - run: npm install
      shell: bash
