name: 'Setup'
description: 'Setup'
runs:
  using: 'composite'
  steps:
    - name:
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config build-essential libudev-dev xvfb
      shell: bash
    - run: git submodule update --init --recursive --depth 1
      shell: bash
